services:
  rf_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rf_bot_watchdog
    network_mode: "host"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGO_URI=${MONGO_URI}
      - OWNER_ID=${OWNER_ID}
      - URL_PREFIX=${URL_PREFIX}
    restart: "on-failure"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
